AWSTemplateFormatVersion: '2010-09-09'
Resources:
  SentinelGlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref "AWS::AccountId"
      DatabaseInput:
        Name: "sentinel_db"

  GlueCrawlerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: S3ReadPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource: 
                  - "arn:aws:s3:::data-master-sentinel-bruno-2026/*"
                  - "arn:aws:s3:::data-master-sentinel-bruno-2026"

  SentinelCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: "sentinel-ssp-crawler"
      Role: !GetAtt GlueCrawlerRole.Arn
      DatabaseName: !Ref SentinelGlueDatabase
      Targets:
        S3Targets:
          - Path: "s3://data-master-sentinel-bruno-2026/trusted/celulares/"
      TablePrefix: "silver_"
      SchemaChangePolicy:
        UpdateBehavior: "UPDATE_IN_DATABASE"
        DeleteBehavior: "DEPRECATE_IN_DATABASE"